### ISSUE TITLE
Implement hook when nuxt-security blocks

### ISSUE THREAD

**Issue by agracia-foticos** [Baroshem/nuxt-security#166]
### Describe the solution you'd like
Implement hook when nuxt-security blocks

**Comment by Baroshem** [comment]
Hey @agracia-foticos 

Could you please add more details to the feature request?

What you would like to achieve with it? What are you missing currently?

**Comment by agracia-foticos** [comment]
We have some request from some crawlers that throws 404 and we dont know what is the cause.

We have implemented nuxt security and we want to log when nuxt security blocks some request

**Comment by Baroshem** [comment]
NuxtSecurity does not throw 404 errors.

These errors are probably coming from the core nuxt. Can you disable the module and see if these kind of errors are still appearing?

**Comment by agracia-foticos** [comment]
Its perfect, thanks for the support :)
