### ISSUE TITLE
Releases section does not work

### ISSUE THREAD

**Issue by Baroshem** [Baroshem/nuxt-security#254]
![image](https://github.com/Baroshem/nuxt-security/assets/37120330/c8adad4e-51c6-48bf-afda-223fbfaead93)

### Version

nuxt-security: 
nuxt:

**Comment by vejja** [comment]
@Baroshem
I looked at this one and as far as I understand, `<GithubReleases>` is basically a headless component so you need to extend it to render something in the page.
I have a POC that displays the releases, but I need to admit that the UI is very basic (not to say extremely poor...). If you want to have a look at it I can push my local branch, let me know if you are interested.

**Comment by vejja** [comment]
@Baroshem 
I pushed the branch here : https://github.com/Baroshem/nuxt-security/tree/poc/github-releases
I am not creating a PR though because I don't think it is really publishable as it stands.

Have a look at it and let me know, but my assessment is
- It does not add so much value
- It would require a lot of work to make it nice UI-wise
- It would be easier to just redirect to Github

It all depends on what you want to see on this page at the end of the day. The API is quite versatile so there is a lot of information that can be fetched and displayed there.

**Comment by Baroshem** [comment]
Hey @vejja 

Thanks for this PoC. I have some strange issues:

```
[Vue warn]: Failed to resolve component: MDCRenderer
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Component <Anonymous> is missing template or render function.
```

It does not matter if I do these changes manually or checkout to your branch, the issues are still there.

I will verify how other modules do this releases section and based on that I will update our Releases page
